// <auto-generated />
using System;
using CATALOGWEB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CATALOGWEB.Migrations
{
    [DbContext(typeof(CatwebContext))]
    partial class CatwebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CATALOGWEB.Models.Rol", b =>
                {
                    b.Property<int>("Idr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDR");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idr"));

                    b.Property<string>("Rol1")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ROL");

                    b.HasKey("Idr")
                        .HasName("PK__ROL__C4971C3CEE7624C9");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("CATALOGWEB.Models.Usuario", b =>
                {
                    b.Property<int>("Idu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idu"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("CORREO");

                    b.Property<string>("Curp")
                        .HasMaxLength(18)
                        .IsUnicode(false)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("CURP");

                    b.Property<int?>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("EDAD");

                    b.Property<string>("Genero")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("GENERO");

                    b.Property<int?>("Idr")
                        .HasColumnType("int")
                        .HasColumnName("IDR");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Idu")
                        .HasName("PK__USUARIO__C4971C39F31E79CE");

                    b.HasIndex("Idr");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("CATALOGWEB.Models.Usuario", b =>
                {
                    b.HasOne("CATALOGWEB.Models.Rol", "oRol")
                        .WithMany("Usuarios")
                        .HasForeignKey("Idr")
                        .HasConstraintName("FK_ROL");

                    b.Navigation("oRol");
                });

            modelBuilder.Entity("CATALOGWEB.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
